# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Frontend/*

pr:
  branches:
    include:
    - main
  paths:
    include:
    - Frontend/*

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- task: Cache@2
  inputs:
    key: $(Build.SourcesDirectory)/Frontend/Portal/package-lock.json
    path: $(Build.SourcesDirectory)/Frontend/Portal/node_modules
    cacheHitVar: CACHE_RESTORED
  displayName: Cache npm

- script: |
    npm install
  workingDirectory: 'Frontend/Portal'
  displayName: 'npm install'
  condition: ne(variables.CACHE_RESTORED, 'true')

- script: |
    npm run build
  workingDirectory: 'Frontend/Portal'
  env:
    GENERATE_SOURCEMAP: false
    VITE_API_BASE_URL: 'https://gaiaproject.azurewebsites.net'
    VITE_AUTH0_DOMAIN: $(REACT_APP_AUTH0_DOMAIN)
    VITE_AUTH0_CLIENT_ID: $(REACT_APP_AUTH0_CLIENT_ID)
    VITE_AUTH0_AUDIENCE: $(REACT_APP_AUTH0_AUDIENCE)
    VITE_AUTH0_SCOPE: $(REACT_APP_AUTH0_SCOPE)
  displayName: 'Production build'

- task: AzureFileCopy@3
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  inputs:
    SourcePath: 'Frontend/Portal/dist'
    azureSubscription: 'Andrea Bertoldo 45€/month (27352222-c6c7-4fed-8669-6cdcd1f93dcf)'
    Destination: 'AzureBlob'
    storage: 'gaiaproject'
    ContainerName: '$web'
    CleanTargetBeforeCopy: true

- task: CmdLine@2
  inputs:
    script: 'git reset --hard'