# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Backend/*

pr:
  branches:
    include:
    - main
  paths:
    include:
    - Backend/*

resources:
- repo: self

variables:
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        containerRegistry: 'Public Docker Hub'
        repository: 'gaia-project'
        Dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
    - task: Docker@2
      condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
      displayName: Build the app to check everything is ok
      inputs:
        command: build
        Dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
