<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<LangVersion>13</LangVersion>
		<RootNamespace>GaiaProject.ViewModels</RootNamespace>
		<AssemblyName>GaiaProject.ViewModels</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Engine\Engine.csproj" />
	</ItemGroup>
</Project>
