import type { GameStateDto } from "./dto/interfaces";

export const gameDto: GameStateDto = <any>{
	players: [
		{
			id: "5fc58972cc86c60001759a76",
			username: "AdminTester",
			raceId: 1,
			isActive: false,
			placement: 2,
			state: {
				currentRoundTurnOrder: 1,
				nextRoundTurnOrder: null,
				hasPassed: true,
				points: 88,
				auctionPoints: null,
				terraformingCost: 3,
				tempTerraformingSteps: null,
				navigationRange: 4,
				rangeBoost: null,
				researchAdvancements: {
					terraformation: 0,
					navigation: 5,
					artificialIntelligence: 0,
					gaiaformation: 2,
					economy: 0,
					science: 0,
				},
				availableGaiaformers: [
					{
						id: 0,
						available: true,
						spentInGaiaArea: false,
						onHexId: null,
					},
				],
				resources: {
					credits: 10,
					ores: 5,
					knowledge: 2,
					qic: 1,
					power: {
						bowl1: 0,
						bowl2: 0,
						bowl3: 1,
						gaiaArea: 0,
						brainstone: null,
						brainstoneSummary: null,
					},
				},
				income: {
					credits: 7,
					ores: 7,
					knowledge: 3,
					qic: 0,
					power: 4,
					powerTokens: 1,
				},
				buildings: {
					mines: 6,
					tradingStations: 1,
					researchLabs: 2,
					planetaryInstitute: true,
					academyLeft: false,
					academyRight: false,
				},
				technologyTiles: [
					{
						id: 6,
						coveredByAdvancedTile: null,
						used: false,
					},
					{
						id: 3,
						coveredByAdvancedTile: null,
						used: false,
					},
				],
				roundBooster: {
					id: 6,
					used: false,
					inactive: false,
				},
				planetaryInstituteActionSpace: null,
				rightAcademyActionSpace: null,
				raceActionSpace: null,
				federationTokens: [
					{
						id: 3,
						usedForTechOrAdvancedTile: true,
					},
					{
						id: 4,
						usedForTechOrAdvancedTile: false,
					},
				],
				usableGaiaformers: 1,
				unlockedGaiaformers: 1,
				usableFederations: 1,
				numFederationTokens: 2,
				knownPlanetTypes: 5,
				colonizedSectors: 6,
				gaiaPlanets: 4,
				additionalInfo: null,
			},
		},
		{
			id: "5fc05a941a2bf300010fef2c",
			username: "Etchelon",
			raceId: 14,
			isActive: false,
			placement: 1,
			state: {
				currentRoundTurnOrder: 2,
				nextRoundTurnOrder: null,
				hasPassed: true,
				points: 215,
				auctionPoints: null,
				terraformingCost: 1,
				tempTerraformingSteps: null,
				navigationRange: 3,
				rangeBoost: null,
				researchAdvancements: {
					terraformation: 5,
					navigation: 4,
					artificialIntelligence: 4,
					gaiaformation: 5,
					economy: 0,
					science: 0,
				},
				availableGaiaformers: [
					{
						id: 0,
						available: true,
						spentInGaiaArea: false,
						onHexId: null,
					},
					{
						id: 1,
						available: true,
						spentInGaiaArea: false,
						onHexId: null,
					},
					{
						id: 2,
						available: true,
						spentInGaiaArea: false,
						onHexId: null,
					},
				],
				resources: {
					credits: 1,
					ores: 0,
					knowledge: 0,
					qic: 0,
					power: {
						bowl1: 0,
						bowl2: 0,
						bowl3: 0,
						gaiaArea: 0,
						brainstone: null,
						brainstoneSummary: null,
					},
				},
				income: {
					credits: 16,
					ores: 9,
					knowledge: 5,
					qic: 0,
					power: 5,
					powerTokens: 4,
				},
				buildings: {
					mines: 7,
					tradingStations: 3,
					researchLabs: 3,
					planetaryInstitute: true,
					academyLeft: false,
					academyRight: false,
				},
				technologyTiles: [
					{
						id: 5,
						coveredByAdvancedTile: null,
						used: false,
					},
					{
						id: 6,
						coveredByAdvancedTile: null,
						used: false,
					},
					{
						id: 8,
						coveredByAdvancedTile: 2,
						used: true,
					},
					{
						id: 4,
						coveredByAdvancedTile: null,
						used: false,
					},
					{
						id: 2,
						coveredByAdvancedTile: 5,
						used: false,
					},
					{
						id: 3,
						coveredByAdvancedTile: null,
						used: false,
					},
					{
						id: 0,
						coveredByAdvancedTile: null,
						used: true,
					},
				],
				roundBooster: {
					id: 1,
					used: false,
					inactive: false,
				},
				planetaryInstituteActionSpace: null,
				rightAcademyActionSpace: null,
				raceActionSpace: null,
				federationTokens: [
					{
						id: 0,
						usedForTechOrAdvancedTile: true,
					},
					{
						id: 3,
						usedForTechOrAdvancedTile: true,
					},
					{
						id: 2,
						usedForTechOrAdvancedTile: true,
					},
					{
						id: 4,
						usedForTechOrAdvancedTile: true,
					},
				],
				usableGaiaformers: 3,
				unlockedGaiaformers: 3,
				usableFederations: 0,
				numFederationTokens: 4,
				knownPlanetTypes: 4,
				colonizedSectors: 5,
				gaiaPlanets: 8,
				additionalInfo: null,
			},
		},
	],
	boardState: {
		map: {
			playerCount: 2,
			rows: 24,
			columns: 14,
			shape: 2,
			sectors: [
				{
					id: "1",
					number: 5,
					rotation: 1,
					row: 15,
					column: 2,
					hexes: [
						{
							id: "1-0",
							index: 0,
							row: 15,
							column: 4,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "1-1",
							index: 1,
							row: 16,
							column: 3,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "1-2",
							index: 2,
							row: 16,
							column: 5,
							planetType: 8,
							wasGaiaformed: true,
							building: {
								username: "AdminTester",
								raceId: 1,
								type: 0,
								powerValue: 1,
								powerValueInFederation: 1,
								federationId: "5fc58972cc86c60001759a76_1",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "1-3",
							index: 3,
							row: 17,
							column: 2,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "1-4",
							index: 4,
							row: 17,
							column: 4,
							planetType: 0,
							wasGaiaformed: false,
							building: {
								username: "AdminTester",
								raceId: 1,
								type: 0,
								powerValue: 1,
								powerValueInFederation: 1,
								federationId: "5fc58972cc86c60001759a76_1",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "1-5",
							index: 5,
							row: 17,
							column: 6,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "AdminTester",
									raceId: 1,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc58972cc86c60001759a76_1",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "1-6",
							index: 6,
							row: 18,
							column: 3,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "1-7",
							index: 7,
							row: 18,
							column: 5,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "1-8",
							index: 8,
							row: 19,
							column: 2,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "1-9",
							index: 9,
							row: 19,
							column: 4,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "1-10",
							index: 10,
							row: 19,
							column: 6,
							planetType: 5,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "1-11",
							index: 11,
							row: 20,
							column: 3,
							planetType: 1,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "1-12",
							index: 12,
							row: 20,
							column: 5,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "1-13",
							index: 13,
							row: 21,
							column: 2,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "1-14",
							index: 14,
							row: 21,
							column: 4,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "1-15",
							index: 15,
							row: 21,
							column: 6,
							planetType: 3,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "1-16",
							index: 16,
							row: 22,
							column: 3,
							planetType: 2,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "1-17",
							index: 17,
							row: 22,
							column: 5,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "1-18",
							index: 18,
							row: 23,
							column: 4,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
					],
				},
				{
					id: "2",
					number: 3,
					rotation: 5,
					row: 8,
					column: 5,
					hexes: [
						{
							id: "2-0",
							index: 0,
							row: 8,
							column: 7,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "2-1",
							index: 1,
							row: 9,
							column: 6,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "2-2",
							index: 2,
							row: 9,
							column: 8,
							planetType: 5,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "2-3",
							index: 3,
							row: 10,
							column: 5,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "AdminTester",
									raceId: 1,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc58972cc86c60001759a76_2",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "2-4",
							index: 4,
							row: 10,
							column: 7,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "2-5",
							index: 5,
							row: 10,
							column: 9,
							planetType: 4,
							wasGaiaformed: false,
							building: {
								username: "Etchelon",
								raceId: 14,
								type: 0,
								powerValue: 1,
								powerValueInFederation: 1,
								federationId: "5fc05a941a2bf300010fef2c_1",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "2-6",
							index: 6,
							row: 11,
							column: 6,
							planetType: 1,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "2-7",
							index: 7,
							row: 11,
							column: 8,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "2-8",
							index: 8,
							row: 12,
							column: 5,
							planetType: 3,
							wasGaiaformed: false,
							building: {
								username: "AdminTester",
								raceId: 1,
								type: 0,
								powerValue: 1,
								powerValueInFederation: 1,
								federationId: "5fc58972cc86c60001759a76_2",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "2-9",
							index: 9,
							row: 12,
							column: 7,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "2-10",
							index: 10,
							row: 12,
							column: 9,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "2-11",
							index: 11,
							row: 13,
							column: 6,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "2-12",
							index: 12,
							row: 13,
							column: 8,
							planetType: 6,
							wasGaiaformed: false,
							building: {
								username: "Etchelon",
								raceId: 14,
								type: 3,
								powerValue: 2,
								powerValueInFederation: 2,
								federationId: "5fc05a941a2bf300010fef2c_3",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "2-13",
							index: 13,
							row: 14,
							column: 5,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "2-14",
							index: 14,
							row: 14,
							column: 7,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "Etchelon",
									raceId: 14,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc05a941a2bf300010fef2c_3",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "2-15",
							index: 15,
							row: 14,
							column: 9,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "Etchelon",
									raceId: 14,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc05a941a2bf300010fef2c_3",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "2-16",
							index: 16,
							row: 15,
							column: 6,
							planetType: 8,
							wasGaiaformed: true,
							building: {
								username: "Etchelon",
								raceId: 14,
								type: 1,
								powerValue: 2,
								powerValueInFederation: 2,
								federationId: "5fc05a941a2bf300010fef2c_3",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "2-17",
							index: 17,
							row: 15,
							column: 8,
							planetType: 2,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "2-18",
							index: 18,
							row: 16,
							column: 7,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
					],
				},
				{
					id: "3",
					number: 4,
					rotation: 1,
					row: 9,
					column: 10,
					hexes: [
						{
							id: "3-0",
							index: 0,
							row: 9,
							column: 12,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "3-1",
							index: 1,
							row: 10,
							column: 11,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "3-2",
							index: 2,
							row: 10,
							column: 13,
							planetType: 4,
							wasGaiaformed: false,
							building: {
								username: "Etchelon",
								raceId: 14,
								type: 0,
								powerValue: 1,
								powerValueInFederation: 1,
								federationId: "5fc05a941a2bf300010fef2c_1",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "3-3",
							index: 3,
							row: 11,
							column: 10,
							planetType: 8,
							wasGaiaformed: true,
							building: {
								username: "Etchelon",
								raceId: 14,
								type: 3,
								powerValue: 2,
								powerValueInFederation: 2,
								federationId: "5fc05a941a2bf300010fef2c_1",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "3-4",
							index: 4,
							row: 11,
							column: 12,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "Etchelon",
									raceId: 14,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc05a941a2bf300010fef2c_1",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "3-5",
							index: 5,
							row: 11,
							column: 14,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "3-6",
							index: 6,
							row: 12,
							column: 11,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "Etchelon",
									raceId: 14,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc05a941a2bf300010fef2c_1",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "3-7",
							index: 7,
							row: 12,
							column: 13,
							planetType: 6,
							wasGaiaformed: false,
							building: {
								username: "Etchelon",
								raceId: 14,
								type: 2,
								powerValue: 3,
								powerValueInFederation: 3,
								federationId: "5fc05a941a2bf300010fef2c_1",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "3-8",
							index: 8,
							row: 13,
							column: 10,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "3-9",
							index: 9,
							row: 13,
							column: 12,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "3-10",
							index: 10,
							row: 13,
							column: 14,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "3-11",
							index: 11,
							row: 14,
							column: 11,
							planetType: 7,
							wasGaiaformed: false,
							building: {
								username: "AdminTester",
								raceId: 1,
								type: 2,
								powerValue: 3,
								powerValueInFederation: 3,
								federationId: "5fc58972cc86c60001759a76_1",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "3-12",
							index: 12,
							row: 14,
							column: 13,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "3-13",
							index: 13,
							row: 15,
							column: 10,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "3-14",
							index: 14,
							row: 15,
							column: 12,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "3-15",
							index: 15,
							row: 15,
							column: 14,
							planetType: 2,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "3-16",
							index: 16,
							row: 16,
							column: 11,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "AdminTester",
									raceId: 1,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc58972cc86c60001759a76_1",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "3-17",
							index: 17,
							row: 16,
							column: 13,
							planetType: 0,
							wasGaiaformed: false,
							building: {
								username: "AdminTester",
								raceId: 1,
								type: 3,
								powerValue: 2,
								powerValueInFederation: 2,
								federationId: "5fc58972cc86c60001759a76_1",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "3-18",
							index: 18,
							row: 17,
							column: 12,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "AdminTester",
									raceId: 1,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc58972cc86c60001759a76_1",
									showFederationMarker: false,
								},
							],
						},
					],
				},
				{
					id: "4",
					number: 2,
					rotation: 0,
					row: 7,
					column: 0,
					hexes: [
						{
							id: "4-0",
							index: 0,
							row: 7,
							column: 2,
							planetType: 4,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "4-1",
							index: 1,
							row: 8,
							column: 1,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "4-2",
							index: 2,
							row: 8,
							column: 3,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "AdminTester",
									raceId: 1,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc58972cc86c60001759a76_2",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "4-3",
							index: 3,
							row: 9,
							column: 0,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "4-4",
							index: 4,
							row: 9,
							column: 2,
							planetType: 3,
							wasGaiaformed: false,
							building: {
								username: "AdminTester",
								raceId: 1,
								type: 0,
								powerValue: 1,
								powerValueInFederation: 1,
								federationId: "5fc58972cc86c60001759a76_2",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "4-5",
							index: 5,
							row: 9,
							column: 4,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "4-6",
							index: 6,
							row: 10,
							column: 1,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "4-7",
							index: 7,
							row: 10,
							column: 3,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "4-8",
							index: 8,
							row: 11,
							column: 0,
							planetType: 6,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "4-9",
							index: 9,
							row: 11,
							column: 2,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "4-10",
							index: 10,
							row: 11,
							column: 4,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "4-11",
							index: 11,
							row: 12,
							column: 1,
							planetType: 5,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "4-12",
							index: 12,
							row: 12,
							column: 3,
							planetType: 1,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "4-13",
							index: 13,
							row: 13,
							column: 0,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "4-14",
							index: 14,
							row: 13,
							column: 2,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "4-15",
							index: 15,
							row: 13,
							column: 4,
							planetType: 0,
							wasGaiaformed: false,
							building: {
								username: "AdminTester",
								raceId: 1,
								type: 0,
								powerValue: 1,
								powerValueInFederation: 1,
								federationId: "5fc58972cc86c60001759a76_2",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "4-16",
							index: 16,
							row: 14,
							column: 1,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "4-17",
							index: 17,
							row: 14,
							column: 3,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "4-18",
							index: 18,
							row: 15,
							column: 2,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
					],
				},
				{
					id: "5outlined",
					number: 6,
					rotation: 4,
					row: 16,
					column: 7,
					hexes: [
						{
							id: "5outlined-0",
							index: 0,
							row: 16,
							column: 9,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "Etchelon",
									raceId: 14,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc05a941a2bf300010fef2c_3",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "5outlined-1",
							index: 1,
							row: 17,
							column: 8,
							planetType: 5,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "5outlined-2",
							index: 2,
							row: 17,
							column: 10,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "AdminTester",
									raceId: 1,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc58972cc86c60001759a76_1",
									showFederationMarker: false,
								},
								{
									username: "Etchelon",
									raceId: 14,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc05a941a2bf300010fef2c_3",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "5outlined-3",
							index: 3,
							row: 18,
							column: 7,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "AdminTester",
									raceId: 1,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc58972cc86c60001759a76_1",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "5outlined-4",
							index: 4,
							row: 18,
							column: 9,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "AdminTester",
									raceId: 1,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc58972cc86c60001759a76_1",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "5outlined-5",
							index: 5,
							row: 18,
							column: 11,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "5outlined-6",
							index: 6,
							row: 19,
							column: 8,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "AdminTester",
									raceId: 1,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc58972cc86c60001759a76_1",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "5outlined-7",
							index: 7,
							row: 19,
							column: 10,
							planetType: 7,
							wasGaiaformed: false,
							building: {
								username: "Etchelon",
								raceId: 14,
								type: 0,
								powerValue: 1,
								powerValueInFederation: 1,
								federationId: "5fc05a941a2bf300010fef2c_3",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "5outlined-8",
							index: 8,
							row: 20,
							column: 7,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "5outlined-9",
							index: 9,
							row: 20,
							column: 9,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "5outlined-10",
							index: 10,
							row: 20,
							column: 11,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "Etchelon",
									raceId: 14,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc05a941a2bf300010fef2c_3",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "5outlined-11",
							index: 11,
							row: 21,
							column: 8,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "5outlined-12",
							index: 12,
							row: 21,
							column: 10,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "5outlined-13",
							index: 13,
							row: 22,
							column: 7,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "5outlined-14",
							index: 14,
							row: 22,
							column: 9,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "5outlined-15",
							index: 15,
							row: 22,
							column: 11,
							planetType: 6,
							wasGaiaformed: false,
							building: {
								username: "Etchelon",
								raceId: 14,
								type: 0,
								powerValue: 1,
								powerValueInFederation: 1,
								federationId: "5fc05a941a2bf300010fef2c_3",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "5outlined-16",
							index: 16,
							row: 23,
							column: 8,
							planetType: 3,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "5outlined-17",
							index: 17,
							row: 23,
							column: 10,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "Etchelon",
									raceId: 14,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc05a941a2bf300010fef2c_3",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "5outlined-18",
							index: 18,
							row: 24,
							column: 9,
							planetType: 8,
							wasGaiaformed: true,
							building: {
								username: "Etchelon",
								raceId: 14,
								type: 0,
								powerValue: 1,
								powerValueInFederation: 1,
								federationId: "5fc05a941a2bf300010fef2c_3",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
					],
				},
				{
					id: "6outlined",
					number: 1,
					rotation: 3,
					row: 1,
					column: 8,
					hexes: [
						{
							id: "6outlined-0",
							index: 0,
							row: 1,
							column: 10,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "6outlined-1",
							index: 1,
							row: 2,
							column: 9,
							planetType: 8,
							wasGaiaformed: true,
							building: {
								username: "Etchelon",
								raceId: 14,
								type: 3,
								powerValue: 2,
								powerValueInFederation: 2,
								federationId: "5fc05a941a2bf300010fef2c_1",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "6outlined-2",
							index: 2,
							row: 2,
							column: 11,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "6outlined-3",
							index: 3,
							row: 3,
							column: 8,
							planetType: 2,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "6outlined-4",
							index: 4,
							row: 3,
							column: 10,
							planetType: 7,
							wasGaiaformed: false,
							building: {
								username: "Etchelon",
								raceId: 14,
								type: 1,
								powerValue: 2,
								powerValueInFederation: 2,
								federationId: "5fc05a941a2bf300010fef2c_1",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "6outlined-5",
							index: 5,
							row: 3,
							column: 12,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "6outlined-6",
							index: 6,
							row: 4,
							column: 9,
							planetType: 9,
							wasGaiaformed: false,
							building: {
								username: "AdminTester",
								raceId: 1,
								type: 8,
								powerValue: 1,
								powerValueInFederation: 1,
								federationId: null,
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "6outlined-7",
							index: 7,
							row: 4,
							column: 11,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "6outlined-8",
							index: 8,
							row: 5,
							column: 8,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "Etchelon",
									raceId: 14,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc05a941a2bf300010fef2c_1",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "6outlined-9",
							index: 9,
							row: 5,
							column: 10,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "Etchelon",
									raceId: 14,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc05a941a2bf300010fef2c_1",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "6outlined-10",
							index: 10,
							row: 5,
							column: 12,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "6outlined-11",
							index: 11,
							row: 6,
							column: 9,
							planetType: 0,
							wasGaiaformed: false,
							building: {
								username: "Etchelon",
								raceId: 14,
								type: 0,
								powerValue: 1,
								powerValueInFederation: 1,
								federationId: "5fc05a941a2bf300010fef2c_1",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "6outlined-12",
							index: 12,
							row: 6,
							column: 11,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "6outlined-13",
							index: 13,
							row: 7,
							column: 8,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "6outlined-14",
							index: 14,
							row: 7,
							column: 10,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "6outlined-15",
							index: 15,
							row: 7,
							column: 12,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "6outlined-16",
							index: 16,
							row: 8,
							column: 9,
							planetType: 8,
							wasGaiaformed: true,
							building: {
								username: "Etchelon",
								raceId: 14,
								type: 0,
								powerValue: 1,
								powerValueInFederation: 1,
								federationId: "5fc05a941a2bf300010fef2c_1",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "6outlined-17",
							index: 17,
							row: 8,
							column: 11,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "6outlined-18",
							index: 18,
							row: 9,
							column: 10,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
					],
				},
				{
					id: "7outlined",
					number: 0,
					rotation: 0,
					row: 0,
					column: 3,
					hexes: [
						{
							id: "7outlined-0",
							index: 0,
							row: 0,
							column: 5,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "7outlined-1",
							index: 1,
							row: 1,
							column: 4,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "7outlined-2",
							index: 2,
							row: 1,
							column: 6,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "7outlined-3",
							index: 3,
							row: 2,
							column: 3,
							planetType: 8,
							wasGaiaformed: true,
							building: {
								username: "AdminTester",
								raceId: 1,
								type: 1,
								powerValue: 2,
								powerValueInFederation: 2,
								federationId: "5fc58972cc86c60001759a76_2",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "7outlined-4",
							index: 4,
							row: 2,
							column: 5,
							planetType: 7,
							wasGaiaformed: false,
							building: {
								username: "Etchelon",
								raceId: 14,
								type: 1,
								powerValue: 2,
								powerValueInFederation: 2,
								federationId: "5fc05a941a2bf300010fef2c_1",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "7outlined-5",
							index: 5,
							row: 2,
							column: 7,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "7outlined-6",
							index: 6,
							row: 3,
							column: 4,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "7outlined-7",
							index: 7,
							row: 3,
							column: 6,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "Etchelon",
									raceId: 14,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc05a941a2bf300010fef2c_1",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "7outlined-8",
							index: 8,
							row: 4,
							column: 3,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "AdminTester",
									raceId: 1,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc58972cc86c60001759a76_2",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "7outlined-9",
							index: 9,
							row: 4,
							column: 5,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "7outlined-10",
							index: 10,
							row: 4,
							column: 7,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "Etchelon",
									raceId: 14,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc05a941a2bf300010fef2c_1",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "7outlined-11",
							index: 11,
							row: 5,
							column: 4,
							planetType: 7,
							wasGaiaformed: false,
							building: {
								username: "AdminTester",
								raceId: 1,
								type: 3,
								powerValue: 2,
								powerValueInFederation: 2,
								federationId: "5fc58972cc86c60001759a76_2",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "7outlined-12",
							index: 12,
							row: 5,
							column: 6,
							planetType: 1,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "7outlined-13",
							index: 13,
							row: 6,
							column: 3,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "7outlined-14",
							index: 14,
							row: 6,
							column: 5,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "7outlined-15",
							index: 15,
							row: 6,
							column: 7,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "7outlined-16",
							index: 16,
							row: 7,
							column: 4,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [
								{
									username: "AdminTester",
									raceId: 1,
									type: 7,
									powerValue: 0,
									powerValueInFederation: 0,
									federationId: "5fc58972cc86c60001759a76_2",
									showFederationMarker: false,
								},
							],
						},
						{
							id: "7outlined-17",
							index: 17,
							row: 7,
							column: 6,
							planetType: null,
							wasGaiaformed: false,
							building: null,
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
						{
							id: "7outlined-18",
							index: 18,
							row: 8,
							column: 5,
							planetType: 4,
							wasGaiaformed: false,
							building: {
								username: "AdminTester",
								raceId: 1,
								type: 0,
								powerValue: 1,
								powerValueInFederation: 1,
								federationId: "5fc58972cc86c60001759a76_2",
								showFederationMarker: false,
							},
							lantidsParasiteBuilding: null,
							ivitsSpaceStation: null,
							satellites: [],
						},
					],
				},
			],
		},
		scoringBoard: {
			scoringTiles: [
				{
					tileId: 7,
					roundNumber: 1,
					inactive: true,
				},
				{
					tileId: 4,
					roundNumber: 2,
					inactive: true,
				},
				{
					tileId: 8,
					roundNumber: 3,
					inactive: true,
				},
				{
					tileId: 1,
					roundNumber: 4,
					inactive: true,
				},
				{
					tileId: 5,
					roundNumber: 5,
					inactive: true,
				},
				{
					tileId: 9,
					roundNumber: 6,
					inactive: false,
				},
			],
			finalScoring1: {
				tileId: 4,
				players: [
					{
						player: {
							id: "5fc58972cc86c60001759a76",
							username: "AdminTester",
							avatarUrl: "Bertoldo",
							raceId: 1,
							raceName: "Terrans",
							color: "blue",
							points: 88,
							isActive: false,
							placement: 2,
						},
						count: 6,
						points: 18,
					},
					{
						player: {
							id: "5fc05a941a2bf300010fef2c",
							username: "Etchelon",
							avatarUrl: "https://vignette.wikia.nocookie.net/factpile/images/f/f8/BlacktempleIllidan.jpg/revision/latest/scale-to-width-down/340?cb=20130430054200",
							raceId: 14,
							raceName: "Itars",
							color: "white",
							points: 215,
							isActive: false,
							placement: 1,
						},
						count: 5,
						points: 12,
					},
				],
			},
			finalScoring2: {
				tileId: 5,
				players: [
					{
						player: {
							id: "5fc05a941a2bf300010fef2c",
							username: "Etchelon",
							avatarUrl: "https://vignette.wikia.nocookie.net/factpile/images/f/f8/BlacktempleIllidan.jpg/revision/latest/scale-to-width-down/340?cb=20130430054200",
							raceId: 14,
							raceName: "Itars",
							color: "white",
							points: 215,
							isActive: false,
							placement: 1,
						},
						count: 12,
						points: 18,
					},
					{
						player: {
							id: "5fc58972cc86c60001759a76",
							username: "AdminTester",
							avatarUrl: "Bertoldo",
							raceId: 1,
							raceName: "Terrans",
							color: "blue",
							points: 88,
							isActive: false,
							placement: 2,
						},
						count: 11,
						points: 12,
					},
				],
			},
		},
		researchBoard: {
			tracks: [
				{
					id: 0,
					players: [
						{
							raceId: 14,
							steps: 5,
						},
						{
							raceId: 1,
							steps: 0,
						},
					],
					standardTiles: {
						type: 0,
						total: 2,
						remaining: 1,
					},
					advancedTileType: 10,
					federation: null,
					lostPlanet: false,
				},
				{
					id: 1,
					players: [
						{
							raceId: 14,
							steps: 4,
						},
						{
							raceId: 1,
							steps: 5,
						},
					],
					standardTiles: {
						type: 5,
						total: 2,
						remaining: 1,
					},
					advancedTileType: 8,
					federation: null,
					lostPlanet: false,
				},
				{
					id: 2,
					players: [
						{
							raceId: 14,
							steps: 4,
						},
						{
							raceId: 1,
							steps: 0,
						},
					],
					standardTiles: {
						type: 2,
						total: 2,
						remaining: 1,
					},
					advancedTileType: null,
					federation: null,
					lostPlanet: false,
				},
				{
					id: 3,
					players: [
						{
							raceId: 14,
							steps: 5,
						},
						{
							raceId: 1,
							steps: 2,
						},
					],
					standardTiles: {
						type: 6,
						total: 2,
						remaining: 0,
					},
					advancedTileType: null,
					federation: null,
					lostPlanet: false,
				},
				{
					id: 4,
					players: [
						{
							raceId: 14,
							steps: 0,
						},
						{
							raceId: 1,
							steps: 0,
						},
					],
					standardTiles: {
						type: 1,
						total: 2,
						remaining: 2,
					},
					advancedTileType: 3,
					federation: null,
					lostPlanet: false,
				},
				{
					id: 5,
					players: [
						{
							raceId: 14,
							steps: 0,
						},
						{
							raceId: 1,
							steps: 0,
						},
					],
					standardTiles: {
						type: 7,
						total: 2,
						remaining: 2,
					},
					advancedTileType: 14,
					federation: null,
					lostPlanet: false,
				},
			],
			freeStandardTiles: [
				{
					type: 3,
					total: 2,
					remaining: 0,
				},
				{
					type: 4,
					total: 2,
					remaining: 1,
				},
				{
					type: 8,
					total: 2,
					remaining: 1,
				},
			],
			powerActions: [
				{
					kind: "power",
					type: 0,
					isAvailable: true,
				},
				{
					kind: "power",
					type: 1,
					isAvailable: true,
				},
				{
					kind: "power",
					type: 2,
					isAvailable: true,
				},
				{
					kind: "power",
					type: 3,
					isAvailable: false,
				},
				{
					kind: "power",
					type: 4,
					isAvailable: true,
				},
				{
					kind: "power",
					type: 5,
					isAvailable: true,
				},
				{
					kind: "power",
					type: 6,
					isAvailable: true,
				},
			],
			qicActions: [
				{
					kind: "qic",
					type: 0,
					isAvailable: true,
				},
				{
					kind: "qic",
					type: 1,
					isAvailable: true,
				},
				{
					kind: "qic",
					type: 2,
					isAvailable: true,
				},
			],
		},
		availableRoundBoosters: [
			{
				id: 3,
				isTaken: false,
				player: null,
				used: false,
			},
			{
				id: 0,
				isTaken: false,
				player: null,
				used: false,
			},
			{
				id: 4,
				isTaken: false,
				player: null,
				used: false,
			},
		],
		availableFederations: [
			{
				type: 2,
				initialQuantity: 2,
				remaining: 2,
			},
			{
				type: 1,
				initialQuantity: 3,
				remaining: 3,
			},
			{
				type: 4,
				initialQuantity: 3,
				remaining: 1,
			},
			{
				type: 3,
				initialQuantity: 3,
				remaining: 1,
			},
			{
				type: 0,
				initialQuantity: 3,
				remaining: 2,
			},
			{
				type: 5,
				initialQuantity: 3,
				remaining: 3,
			},
		],
	},
	activePlayer: null,
	gameLogs: [
		{
			timestamp: "10/03/2022 12:37",
			message: "performs conversions",
			important: false,
			isSystem: false,
			actionId: 186,
			turn: 92,
			player: "Etchelon",
			race: 14,
			subLogs: [
				{
					timestamp: "10/03/2022 12:37",
					message: "performs conversions. Spends 4 power to earn 4 credits",
					player: "Etchelon",
					race: 14,
				},
			],
		},
		{
			timestamp: "10/03/2022 12:38",
			message: "forms a federation",
			important: false,
			isSystem: false,
			actionId: 187,
			turn: 92,
			player: "Etchelon",
			race: 14,
			subLogs: [
				{
					timestamp: "10/03/2022 12:38",
					message: "spends power tokens, which are removed from the player's board: 4 from bowl 1",
					player: "Etchelon",
					race: 14,
				},
				{
					timestamp: "10/03/2022 12:38",
					message: "gains federation token PowerTokens which grants:\n2 power tokens\n8VP (federation PowerTokens)\n5VP (Scoring Tile)",
					player: "Etchelon",
					race: 14,
				},
			],
		},
		{
			timestamp: "10/03/2022 12:38",
			message: "researches technology Terraformation",
			important: false,
			isSystem: false,
			actionId: 189,
			turn: 93,
			player: "Etchelon",
			race: 14,
			subLogs: [
				{
					timestamp: "10/03/2022 12:38",
					message: "spends 4 knowledge",
					player: "Etchelon",
					race: 14,
				},
				{
					timestamp: "10/03/2022 12:38",
					message: "spends a federation token, which is now used",
					player: "Etchelon",
					race: 14,
				},
				{
					timestamp: "10/03/2022 12:38",
					message: "gains federation token Ores which grants:\n2 ores\n7VP (federation Ores)\n5VP (Scoring Tile)",
					player: "Etchelon",
					race: 14,
				},
				{
					timestamp: "10/03/2022 12:38",
					message: "takes the federation token on the Terraformation track",
					player: "Etchelon",
					race: 14,
				},
			],
		},
		{
			timestamp: "10/03/2022 12:39",
			message: "builds a mine on hex 5outlined-18",
			important: false,
			isSystem: false,
			actionId: 191,
			turn: 94,
			player: "Etchelon",
			race: 14,
			subLogs: [
				{
					timestamp: "10/03/2022 12:39",
					message: "spends 2 credits, 1 ores",
					player: "Etchelon",
					race: 14,
				},
				{
					timestamp: "10/03/2022 12:39",
					message: "gains 3VP (Standard tile)",
					player: "Etchelon",
					race: 14,
				},
			],
		},
		{
			timestamp: "10/03/2022 12:39",
			message: "builds a mine on hex 5outlined-15",
			important: false,
			isSystem: false,
			actionId: 192,
			turn: 95,
			player: "Etchelon",
			race: 14,
			subLogs: [
				{
					timestamp: "10/03/2022 12:39",
					message: "spends 2 credits, 1 ores",
					player: "Etchelon",
					race: 14,
				},
			],
		},
		{
			timestamp: "10/03/2022 12:39",
			message: "builds a Trading Station on hex 2-16",
			important: false,
			isSystem: false,
			actionId: 193,
			turn: 96,
			player: "Etchelon",
			race: 14,
			subLogs: [
				{
					timestamp: "10/03/2022 12:39",
					message: "spends 3 credits, 2 ores",
					player: "Etchelon",
					race: 14,
				},
				{
					timestamp: "10/03/2022 12:39",
					message: "gains 1 power",
					player: "AdminTester",
					race: 1,
				},
			],
		},
		{
			timestamp: "10/03/2022 12:40",
			message: "performs conversions",
			important: false,
			isSystem: false,
			actionId: 194,
			turn: 97,
			player: "Etchelon",
			race: 14,
			subLogs: [
				{
					timestamp: "10/03/2022 12:40",
					message: "performs conversions. Spends 2 power to earn 2 credits",
					player: "Etchelon",
					race: 14,
				},
			],
		},
		{
			timestamp: "10/03/2022 12:41",
			message: "performs conversions",
			important: false,
			isSystem: false,
			actionId: 195,
			turn: 97,
			player: "Etchelon",
			race: 14,
			subLogs: [
				{
					timestamp: "10/03/2022 12:41",
					message: "performs conversions. Spends 2 ores to earn 2 power tokens",
					player: "Etchelon",
					race: 14,
				},
			],
		},
		{
			timestamp: "10/03/2022 12:41",
			message: "performs conversions",
			important: false,
			isSystem: false,
			actionId: 196,
			turn: 97,
			player: "Etchelon",
			race: 14,
			subLogs: [
				{
					timestamp: "10/03/2022 12:41",
					message: "performs conversions. Spends 2 knowledge to earn 2 credits",
					player: "Etchelon",
					race: 14,
				},
			],
		},
		{
			timestamp: "10/03/2022 12:42",
			message: "forms a federation",
			important: false,
			isSystem: false,
			actionId: 197,
			turn: 97,
			player: "Etchelon",
			race: 14,
			subLogs: [
				{
					timestamp: "10/03/2022 12:42",
					message: "spends power tokens, which are removed from the player's board: 6 from bowl 1",
					player: "Etchelon",
					race: 14,
				},
				{
					timestamp: "10/03/2022 12:42",
					message: "gains federation token Qic which grants:\n1 qic\n8VP (federation Qic)\n5VP (Scoring Tile)",
					player: "Etchelon",
					race: 14,
				},
			],
		},
		{
			timestamp: "10/03/2022 12:42",
			message: "performs conversions",
			important: false,
			isSystem: false,
			actionId: 198,
			turn: 97,
			player: "Etchelon",
			race: 14,
			subLogs: [
				{
					timestamp: "10/03/2022 12:42",
					message: "performs conversions. Spends 1 qic to earn 1 ores",
					player: "Etchelon",
					race: 14,
				},
			],
		},
		{
			timestamp: "10/03/2022 12:42",
			message: "builds a mine on hex 6outlined-16",
			important: false,
			isSystem: false,
			actionId: 199,
			turn: 98,
			player: "Etchelon",
			race: 14,
			subLogs: [
				{
					timestamp: "10/03/2022 12:42",
					message: "spends 2 credits, 1 ores",
					player: "Etchelon",
					race: 14,
				},
				{
					timestamp: "10/03/2022 12:42",
					message: "gains 3VP (Standard tile)",
					player: "Etchelon",
					race: 14,
				},
				{
					timestamp: "10/03/2022 12:42",
					message: "gains 1 power",
					player: "AdminTester",
					race: 1,
				},
			],
		},
		{
			timestamp: "10/03/2022 12:42",
			message: "builds a Research Lab on hex 6outlined-1",
			important: false,
			isSystem: false,
			actionId: 200,
			turn: 99,
			player: "Etchelon",
			race: 14,
			subLogs: [
				{
					timestamp: "10/03/2022 12:42",
					message: "spends 5 credits, 3 ores",
					player: "Etchelon",
					race: 14,
				},
				{
					timestamp: "10/03/2022 12:42",
					message: "gains 1 power",
					player: "AdminTester",
					race: 1,
				},
			],
		},
		{
			timestamp: "10/03/2022 12:42",
			message: "acquires advanced tile $5VP x Federation, covering tile 1 Knw x planet type",
			important: false,
			isSystem: false,
			actionId: 201,
			turn: 99,
			player: "Etchelon",
			race: 14,
			subLogs: [
				{
					timestamp: "10/03/2022 12:42",
					message: "spends a federation token, which is now used",
					player: "Etchelon",
					race: 14,
				},
				{
					timestamp: "10/03/2022 12:42",
					message: "gains 20VP (advanced tile Immediate5PointsPerFederation)",
					player: "Etchelon",
					race: 14,
				},
			],
		},
		{
			timestamp: "10/03/2022 12:43",
			message: "researches technology Gaiaformation",
			important: false,
			isSystem: false,
			actionId: 202,
			turn: 99,
			player: "Etchelon",
			race: 14,
			subLogs: [
				{
					timestamp: "10/03/2022 12:43",
					message: "spends a federation token, which is now used",
					player: "Etchelon",
					race: 14,
				},
				{
					timestamp: "10/03/2022 12:43",
					message: "gains 12VP (Gaiaformation technology level 5)",
					player: "Etchelon",
					race: 14,
				},
			],
		},
		{
			timestamp: "10/03/2022 12:43",
			message: "passes and finishes its game",
			important: false,
			isSystem: false,
			actionId: 204,
			turn: 100,
			player: "Etchelon",
			race: 14,
			subLogs: [],
		},
		{
			timestamp: "10/03/2022 12:43",
			message: "Final Scoring",
			important: true,
			isSystem: true,
			actionId: null,
			turn: null,
			player: null,
			race: null,
			subLogs: null,
		},
		{
			timestamp: "10/03/2022 12:43",
			message: "Objective 1: Number of sectors with at least 1 colonized planet",
			important: false,
			isSystem: true,
			actionId: null,
			turn: null,
			player: null,
			race: null,
			subLogs: null,
		},
		{
			timestamp: "10/03/2022 12:43",
			message: "gains 15",
			important: false,
			isSystem: false,
			actionId: null,
			turn: 100,
			player: "AdminTester",
			race: 1,
			subLogs: [],
		},
		{
			timestamp: "10/03/2022 12:43",
			message: "gains 6",
			important: false,
			isSystem: false,
			actionId: null,
			turn: 100,
			player: "Etchelon",
			race: 14,
			subLogs: [],
		},
		{
			timestamp: "10/03/2022 12:43",
			message: "Objective 2: Number of satellites used to form federations",
			important: false,
			isSystem: true,
			actionId: null,
			turn: null,
			player: null,
			race: null,
			subLogs: null,
		},
		{
			timestamp: "10/03/2022 12:43",
			message: "gains 18",
			important: false,
			isSystem: false,
			actionId: null,
			turn: 100,
			player: "Etchelon",
			race: 14,
			subLogs: [],
		},
		{
			timestamp: "10/03/2022 12:43",
			message: "gains 12",
			important: false,
			isSystem: false,
			actionId: null,
			turn: 100,
			player: "AdminTester",
			race: 1,
			subLogs: [],
		},
		{
			timestamp: "10/03/2022 12:43",
			message: "Technology Tracks",
			important: false,
			isSystem: true,
			actionId: null,
			turn: null,
			player: null,
			race: null,
			subLogs: null,
		},
		{
			timestamp: "10/03/2022 12:43",
			message: "gains 12 points for 3 steps above level 2",
			important: false,
			isSystem: false,
			actionId: null,
			turn: 100,
			player: "AdminTester",
			race: 1,
			subLogs: [],
		},
		{
			timestamp: "10/03/2022 12:43",
			message: "gains 40 points for 10 steps above level 2",
			important: false,
			isSystem: false,
			actionId: null,
			turn: 100,
			player: "Etchelon",
			race: 14,
			subLogs: [],
		},
		{
			timestamp: "10/03/2022 12:43",
			message: "Remaining resources",
			important: false,
			isSystem: true,
			actionId: null,
			turn: null,
			player: null,
			race: null,
			subLogs: null,
		},
		{
			timestamp: "10/03/2022 12:43",
			message: "gains 6 points for leftover resources",
			important: false,
			isSystem: false,
			actionId: null,
			turn: 100,
			player: "AdminTester",
			race: 1,
			subLogs: [],
		},
		{
			timestamp: "10/03/2022 12:43",
			message: "gains 0 points for leftover resources",
			important: false,
			isSystem: false,
			actionId: null,
			turn: 100,
			player: "Etchelon",
			race: 14,
			subLogs: [],
		},
		{
			timestamp: "10/03/2022 12:43",
			message: "Auction costs",
			important: false,
			isSystem: true,
			actionId: null,
			turn: null,
			player: null,
			race: null,
			subLogs: null,
		},
	],
	auctionState: null,
	currentRound: 6,
	id: "6225ea932f259634877e0e31",
	name: "Mobx #1",
	createdBy: {
		id: "5fc58972cc86c60001759a76",
		username: "AdminTester",
		avatar: "Bertoldo",
		firstName: "Andrea",
		lastName: "https://s.gravatar.com/avatar/c3b0660fa7527575dcc49eed98658fbe?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fan.png",
		memberSince: "2020-12-01T00:08:18.544Z",
	},
	created: "2022-03-07T11:20:51.091Z",
	ended: "2022-03-10T00:43:10.998Z",
	currentPhase: 1,
};
