<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
	<LangVersion>13</LangVersion>
    <PackageId>SupabaseBackend</PackageId>
    <PackageVersion>1.0.0</PackageVersion>
    <Authors>GaiaProject Team</Authors>
    <Description>A generic repository implementation using the Supabase C# client library.</Description>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReleaseNotes>Initial version with .NET 9 support.</PackageReleaseNotes>
    <Copyright>Copyright 2025 (c) GaiaProject Team. All rights reserved.</Copyright>
    <PackageTags>Supabase Repository Generic Database</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Supabase" Version="1.1.1" />
  </ItemGroup>

</Project>
